// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGeneration(arg1) {
  return window['go']['main']['App']['CancelGeneration'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function FetchModels(arg1, arg2) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAvailableModels(arg1, arg2) {
  return window['go']['main']['App']['ListAvailableModels'](arg1, arg2);
}

export function ListHistory(arg1) {
  return window['go']['main']['App']['ListHistory'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function OpenImage(arg1) {
  return window['go']['main']['App']['OpenImage'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function StartGeneration(arg1) {
  return window['go']['main']['App']['StartGeneration'](arg1);
}

export function TestProfile(arg1) {
  return window['go']['main']['App']['TestProfile'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}
