// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelGeneration(arg1:string):Promise<void>;

export function CreateProfile(arg1:main.ProfileInput):Promise<main.Profile>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function FetchModels(arg1:string,arg2:main.ProfileInput):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListAvailableModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListHistory(arg1:main.HistoryQuery):Promise<main.HistoryPage>;

export function ListProfiles():Promise<Array<main.Profile>>;

export function OpenImage(arg1:string):Promise<void>;

export function SaveImage(arg1:string):Promise<string>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function StartGeneration(arg1:main.GenerationRequest):Promise<main.GenerationJob>;

export function TestProfile(arg1:main.ProfileInput):Promise<main.TestResult>;

export function UpdateProfile(arg1:string,arg2:main.ProfileInput):Promise<main.Profile>;
